[package]
name = "nommy-tests"
version = "0.1.0"
authors = ["Conrad Ludgate <conradludgate@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
nommy = { path = "../nommy" }
trybuild = "1.0"
